name: BrowserStack
on:
  push:
    paths:
      - 'js/**'
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  browserstack:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Bail early
        run: exit 0
        if: github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]'

      - name: Clone repository
        uses: actions/checkout@v2
        if: "!(github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]')"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm
        if: "!(github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]')"

      - run: node --version
      - run: npm --version
        if: "!(github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]')"

      - name: Install npm dependencies
        run: npm ci
        if: "!(github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]')"

      - name: Run dist
        run: npm run dist
        if: "!(github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]')"

      - name: Run BrowserStack tests
        run: npm run js-test-cloud
        env:
          BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
          BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"
          GITHUB_SHA: "${{ github.sha }}"
        if: "!(github.event_name == 'pull_request' || contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:browserstack') || github.actor == 'dependabot[bot]')"
