name: Tests
on:
  push:
    paths:
      - 'js/**'
      - 'scss/**'
      - 'site/content/docs/**/components'
      - 'site/content/docs/**/forms'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    # branches-ignore:
    #   - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  percy:
    runs-on: ubuntu-latest

    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci') && !contains(github.event.pull_request.labels.*.name, 'skip:percy'))) && github.actor != 'louismaximepiton'
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        if: github.event.pull_request.draft == false

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"
        if: github.event.pull_request.draft == false

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        run: npm ci
        if: github.event.pull_request.draft == false

      - name: Compile dist
        run: npm run dist
        if: github.event.pull_request.draft == false

      - name: Build docs
        run: npm run docs-build
        if: github.event.pull_request.draft == false

      - name: Percy Test
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "_site/"
          flags: "--snapshot-files ./docs/**/components/**/*.html,./docs/**/forms/**/*.html"
          verbose: true
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
        if: github.event.pull_request.draft == false
