name: Percy
on:
  push:
    paths:
      - 'js/**'
      - 'scss/**'
      - 'site/content/docs/**/components/**'
      - 'site/content/docs/**/forms/**'
    branches:
      - main
      - v4-dev
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  percy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        run: npm ci

      - name: Compile dist
        run: npm run dist

      - name: Build docs
        run: npm run docs-build

      - name: Percy Test
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "_site/"
          flags: "--snapshot-files ./docs/**/components/**/*.html,./docs/**/forms/**/*.html"
          verbose: true
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
